package Automata.FA;

import Automata.RichAlphabet;
import it.unimi.dsi.fastutil.ints.Int2ObjectMap;
import it.unimi.dsi.fastutil.ints.IntList;

import static Main.UtilityMethods.MISSING_ELT;

import java.util.*;
import java.util.function.IntPredicate;

/**
 * Detects whether a finite automaton accepts infinitely many words.
 * If the language is infinite, this class returns a regex of the form
 *   prefix(cycle)*suffix
 * where every word generated by that regex is accepted by the automaton.
 * The regex is not meant to describe the whole accepted language.
 */
public class Infinite {
  private static final int UNSEEN = 0; // the state has not been reached by the DFS yet
  private static final int ON_STACK = 1; // the state is currently on the recursive DFS path
  private static final int DONE = 2; // the state and all states reachable from it have been explored

  /**
   * Returns a regex for infinitely many accepted values, or "" if the language is finite.
   * After trimming, every remaining state is reachable from q0 and can reach an accepting state.
   * So the language is infinite iff the remaining graph contains a non-empty directed cycle.
   */
  public static String infinite(FA fa, RichAlphabet r) {
    FA work = fa.clone();
    Trimmer.trimAutomaton(work);
    return infiniteTrimmed(work, r);
  }

  /**
   * Once a cycle is found, the accepted infinite family has this shape:
   *   q0 --prefix--> cycle.start --cycle*--> cycle.start --suffix--> final
   * The DFS parent arrays from findCycle() already contain the path from q0 to
   * cycle.start, so we only need one additional BFS to find a suffix from the
   * cycle start to some accepting state.
   */
  private static String infiniteTrimmed(FA fa, RichAlphabet r) {
    if (fa.getQ() == 0 || fa.getQ0() < 0 || fa.getQ0() >= fa.getQ()) {
      return "";
    }

    int[] visitState = new int[fa.getQ()];
    int[] previous = createAndInitArray(fa.getQ()); // predecessor state
    int[] input = createAndInitArray(fa.getQ()); // encoded symbol on the transition previous[q] --input[q]--> q
    previous[fa.getQ0()] = fa.getQ0();

    Cycle cycle = findCycle(fa, fa.getQ0(), visitState, previous, input);
    if (cycle == null) {
      return "";
    }

    List<Integer> prefix = symbolsOnPath(fa.getQ0(), cycle.start, previous, input);
    List<Integer> suffix = findPath(fa, cycle.start, fa::isAccepting);

    return decode(prefix, r) + "(" + decode(cycle.symbols, r) + ")*" + decode(suffix, r);
  }

  /**
   * Runs DFS from current and returns the first directed cycle found.
   * The cycle is detected by a back edge current --symbol--> next, where next is already ON_STACK.
   * At that point, the DFS parent arrays describe the path next -> ... -> current
   * and the back edge closes the loop back to next.
   */
  private static Cycle findCycle(FA fa, int current, int[] visitState, int[] previous, int[] input) {
    visitState[current] = ON_STACK;

    for (Int2ObjectMap.Entry<IntList> entry : fa.getT().getEntriesNfaD(current)) {
      int symbol = entry.getIntKey();
      for (int next : entry.getValue()) {
        if (visitState[next] == UNSEEN) {
          previous[next] = current;
          input[next] = symbol;
          Cycle cycle = findCycle(fa, next, visitState, previous, input);
          if (cycle != null) {
            return cycle;
          }
        } else if (visitState[next] == ON_STACK) {
          List<Integer> cycleSymbols = symbolsOnPath(next, current, previous, input); // next -> ... -> current
          cycleSymbols.add(symbol); // close the cycle with current --symbol--> next
          return new Cycle(next, cycleSymbols);
        }
      }
    }

    // No cycle was found through current; future DFS branches do not need to inspect it again.
    visitState[current] = DONE;
    return null;
  }

  /**
   * Finds a shortest path from start to any state satisfying isTarget.
   * The returned list contains encoded alphabet symbols, not states.
   * Used to find the suffix from the cycle state to an accepting state.
   */
  private static List<Integer> findPath(FA fa, int start, IntPredicate isTarget) {
    if (isTarget.test(start)) {
      return new ArrayList<>();
    }

    int[] previous = createAndInitArray(fa.getQ());
    int[] input = createAndInitArray(fa.getQ());

    Queue<Integer> queue = new ArrayDeque<>();
    previous[start] = start;
    queue.add(start);

    while (!queue.isEmpty()) {
      int current = queue.remove();
      for (Int2ObjectMap.Entry<IntList> entry : fa.getT().getEntriesNfaD(current)) {
        int symbol = entry.getIntKey();
        for (int next : entry.getValue()) {
          if (previous[next] != MISSING_ELT) {
            continue;
          }
          previous[next] = current;
          input[next] = symbol;
          if (isTarget.test(next)) {
            return symbolsOnPath(start, next, previous, input);
          }
          queue.add(next);
        }
      }
    }

    return null;
  }

  private static int[] createAndInitArray(int size) {
    int[] previous = new int[size];
    Arrays.fill(previous, MISSING_ELT);
    return previous;
  }

  /**
   * Reconstructs the encoded symbols on a known path from start to end.
   * For each reached state q, previous[q] is the preceding state and input[q] is the symbol used to enter q.
   * We walk backward from end to start, then reverse the symbols.
   */
  private static List<Integer> symbolsOnPath(int start, int end, int[] previous, int[] input) {
    List<Integer> symbols = new ArrayList<>();
    for (int q = end; q != start; q = previous[q]) {
      symbols.add(input[q]);
    }
    Collections.reverse(symbols);
    return symbols;
  }

  private static String decode(List<Integer> symbols, RichAlphabet r) {
    StringBuilder result = new StringBuilder();
    for (int symbol : symbols) {
      result.append(r.decode(symbol));
    }
    return result.toString();
  }

  private record Cycle(int start, List<Integer> symbols) { }
}
